spring:
  datasource:
    url: jdbc:mysql://{prod_ip}:3306/sf_food_trucks_db
    username: {prod_user}
    password: {prod_user_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true